version: '3'

services:
  nginx:
    image: nginx:1.23
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/master1/nginx/default.conf:/etc/nginx/conf.d/default.conf


  